export const CREATE_QUESTION_SUCCESS = 'CREATE _QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE _QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE _QUESTION_SUCCESS';
export const LOAD_QUESTIONS_SUCCESS ='LOAD_QUESTIONS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
